### ISSUE TITLE
Error while at the 3 step in installation

### ISSUE THREAD

**Issue by solomonricky** [Ciyou/chatbot-telegram#2]
```
root@ChatGPT:~/chatbot-telegram# deno cache --lock=lock.json
error: The following required arguments were not provided:
    <file>...

USAGE:
    deno cache --lock [<FILE>...] <file>...

For more information try --help

root@ChatGPT:~/chatbot-telegram# deno --version
deno 1.30.3 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
root@ChatGPT:~/chatbot-telegram#
```

Unable to proceed this step. Did I mistake somewhere?

**Comment by fenjuly** [comment]
same error,
finally, I use this command, then works
`deno cache --lock=lock.json lock.json`

**Comment by Ciyou** [comment]
Sorry for the inconvenience, there was a typo. The proper command to cache deno depencies is `deno cache --lock=lock.json chatbot.ts`. I've update the readme file, thanks for the feedback! ❤️
